// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2yhbwgmB2di22DNeEjCc7TvmfjTUh8D4',
    appId: '1:993334441344:web:995d26070cc3a3e764fd65',
    messagingSenderId: '993334441344',
    projectId: 'calculator-a995f',
    authDomain: 'calculator-a995f.firebaseapp.com',
    storageBucket: 'calculator-a995f.appspot.com',
    measurementId: 'G-7SHDV0H53K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2qn7VXFjcqx-Zgr3-1PYExavUtbcdwKU',
    appId: '1:993334441344:android:29c01ccddcf7145164fd65',
    messagingSenderId: '993334441344',
    projectId: 'calculator-a995f',
    storageBucket: 'calculator-a995f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmcEqQBQZ-BsLHdk5PfMNtOpnT-7Qr6Yk',
    appId: '1:993334441344:ios:e1a8d8eacedafa8764fd65',
    messagingSenderId: '993334441344',
    projectId: 'calculator-a995f',
    storageBucket: 'calculator-a995f.appspot.com',
    iosBundleId: 'com.example.calculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmcEqQBQZ-BsLHdk5PfMNtOpnT-7Qr6Yk',
    appId: '1:993334441344:ios:7f4eb506990199aa64fd65',
    messagingSenderId: '993334441344',
    projectId: 'calculator-a995f',
    storageBucket: 'calculator-a995f.appspot.com',
    iosBundleId: 'com.example.calculator.RunnerTests',
  );
}
